### ISSUE TITLE
Is it possible to pass any value?

### ISSUE THREAD

**Issue by linonetwo** [ScottyFillups/FastNoiseJS#18]
for example `noise.GetNoise(8888888, 999999999)`

**Comment by philipjscott** [comment]
FastNoiseJS is a wrapper for this repository: https://github.com/Auburn/FastNoise

I believe you can pass in arbitrary numeric values. Here's the library's header file if you're curious: https://github.com/ScottyFillups/FastNoiseJS/blob/master/vendor/FastNoise.h

**Comment by linonetwo** [comment]
Wow, so it is basically a hash function. Thanks.
